[2023-03-22T12:30:08.315+0000] {processor.py:153} INFO - Started process (PID=53548) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:30:08.319+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:30:08.324+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:30:08.323+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:30:09.132+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:30:09.124+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:30:09.159+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:30:09.894+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:30:09.894+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:30:09.980+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:30:09.980+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:30:10.050+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.756 seconds
[2023-03-22T12:30:41.216+0000] {processor.py:153} INFO - Started process (PID=53609) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:30:41.225+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:30:41.252+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:30:41.243+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:30:42.232+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:30:42.228+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:30:42.250+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:30:42.583+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:30:42.582+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:30:42.642+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:30:42.642+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:30:42.681+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.503 seconds
[2023-03-22T12:31:14.114+0000] {processor.py:153} INFO - Started process (PID=53677) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:31:14.121+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:31:14.132+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:31:14.130+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:31:16.708+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:31:16.678+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:31:16.788+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:31:17.245+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:31:17.238+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:31:17.404+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:31:17.404+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:31:17.503+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.409 seconds
[2023-03-22T12:31:48.304+0000] {processor.py:153} INFO - Started process (PID=53739) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:31:48.314+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:31:48.323+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:31:48.323+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:31:50.948+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:31:50.946+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:31:50.970+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:31:51.049+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:31:51.048+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:31:51.163+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:31:51.162+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:31:51.503+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.239 seconds
[2023-03-22T12:32:22.182+0000] {processor.py:153} INFO - Started process (PID=53801) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:32:22.202+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:32:22.210+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:32:22.210+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:32:23.150+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:32:23.148+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:32:23.164+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:32:23.414+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:32:23.413+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:32:23.479+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:32:23.479+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:32:23.524+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.353 seconds
[2023-03-22T12:32:53.669+0000] {processor.py:153} INFO - Started process (PID=53862) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:32:53.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:32:53.681+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:32:53.680+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:32:54.389+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:32:54.385+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:32:54.410+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:32:54.829+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:32:54.828+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:32:54.934+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:32:54.934+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:32:55.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.363 seconds
[2023-03-22T12:33:25.425+0000] {processor.py:153} INFO - Started process (PID=53923) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:33:25.438+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:33:25.448+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:33:25.446+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:33:27.278+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:33:27.267+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:33:27.330+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:33:27.670+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:33:27.666+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:33:27.738+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:33:27.738+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:33:27.824+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.410 seconds
[2023-03-22T12:33:58.069+0000] {processor.py:153} INFO - Started process (PID=53987) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:33:58.073+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:33:58.078+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:33:58.077+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:33:59.186+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:33:59.178+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:33:59.207+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:33:59.273+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:33:59.272+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:33:59.338+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:33:59.338+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:33:59.378+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.330 seconds
[2023-03-22T12:34:31.266+0000] {processor.py:153} INFO - Started process (PID=54047) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:34:31.272+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:34:31.277+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:34:31.276+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:34:32.425+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:34:32.420+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:34:32.439+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:34:32.904+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:34:32.898+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:34:33.076+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:34:33.076+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:34:33.139+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.889 seconds
[2023-03-22T12:35:06.091+0000] {processor.py:153} INFO - Started process (PID=54110) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:35:06.142+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:35:06.173+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:35:06.172+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:35:07.332+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:35:07.321+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:35:07.904+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:35:07.983+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:35:07.982+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:35:08.100+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:35:08.099+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:35:08.167+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.090 seconds
[2023-03-22T12:35:42.732+0000] {processor.py:153} INFO - Started process (PID=54167) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:35:42.737+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:35:42.742+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:35:42.741+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:35:45.855+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:35:45.850+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:35:45.869+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:35:46.016+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:35:46.015+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:35:46.080+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:35:46.080+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:35:46.186+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.468 seconds
[2023-03-22T12:36:16.648+0000] {processor.py:153} INFO - Started process (PID=54228) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:36:16.653+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:36:16.661+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:36:16.660+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:36:18.511+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:36:18.507+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:36:18.528+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:36:18.616+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:36:18.615+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:36:18.726+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:36:18.726+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:36:18.788+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.170 seconds
[2023-03-22T12:36:49.115+0000] {processor.py:153} INFO - Started process (PID=54289) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:36:49.123+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:36:49.126+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:36:49.126+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:36:51.974+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:36:51.966+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:36:52.002+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:36:52.200+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:36:52.199+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:36:52.264+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:36:52.264+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:36:52.324+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.238 seconds
[2023-03-22T12:37:23.077+0000] {processor.py:153} INFO - Started process (PID=54358) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:37:23.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:37:23.097+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:37:23.091+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:37:24.409+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:37:24.402+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:37:25.061+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:37:25.147+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:37:25.145+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:37:25.373+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:37:25.372+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:37:25.470+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.431 seconds
[2023-03-22T12:37:56.515+0000] {processor.py:153} INFO - Started process (PID=54418) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:37:56.521+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:37:56.526+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:37:56.526+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:37:58.309+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:37:58.306+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:37:58.339+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:37:58.592+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:37:58.591+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:37:58.712+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:37:58.711+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:37:58.839+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.361 seconds
[2023-03-22T12:38:29.165+0000] {processor.py:153} INFO - Started process (PID=54479) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:38:29.177+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:38:29.182+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:38:29.181+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:38:30.083+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:38:30.079+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:38:30.102+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:38:30.161+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:38:30.160+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:38:30.220+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:38:30.220+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:38:30.262+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.112 seconds
[2023-03-22T12:39:00.534+0000] {processor.py:153} INFO - Started process (PID=54540) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:39:00.542+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:39:00.548+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:39:00.547+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:39:01.438+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:39:01.434+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:39:01.456+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:39:01.660+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:39:01.658+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:39:01.722+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:39:01.721+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:39:01.777+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.256 seconds
[2023-03-22T12:39:31.952+0000] {processor.py:153} INFO - Started process (PID=54601) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:39:31.957+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:39:31.969+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:39:31.968+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:39:33.069+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:39:33.047+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:39:33.105+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:39:33.192+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:39:33.191+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:39:33.276+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:39:33.275+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:39:33.321+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.398 seconds
[2023-03-22T12:40:03.910+0000] {processor.py:153} INFO - Started process (PID=54662) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:40:03.919+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:40:03.924+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:40:03.924+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:40:04.834+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:40:04.831+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:40:04.848+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:40:05.266+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:40:05.265+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:40:05.340+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:40:05.340+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:40:05.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.502 seconds
[2023-03-22T12:40:36.169+0000] {processor.py:153} INFO - Started process (PID=54723) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:40:36.175+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:40:36.181+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:40:36.181+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:40:37.160+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:40:37.148+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:40:37.180+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:40:37.240+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:40:37.240+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:40:37.295+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:40:37.295+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:40:37.339+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.186 seconds
[2023-03-22T12:41:07.494+0000] {processor.py:153} INFO - Started process (PID=54784) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:41:07.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:41:07.504+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:41:07.503+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:41:08.399+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:41:08.395+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:41:08.421+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:41:08.558+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:41:08.557+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:41:08.617+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:41:08.616+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:41:08.667+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.183 seconds
[2023-03-22T12:41:39.334+0000] {processor.py:153} INFO - Started process (PID=54845) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:41:39.341+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:41:39.348+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:41:39.346+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:41:40.862+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:41:40.846+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:41:40.902+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:41:41.106+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:41:41.105+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:41:41.167+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:41:41.167+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:41:41.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.923 seconds
[2023-03-22T12:42:12.029+0000] {processor.py:153} INFO - Started process (PID=54906) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:42:12.046+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:42:12.070+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:42:12.070+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:42:14.564+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:42:14.561+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:42:14.588+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:42:14.690+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:42:14.689+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:42:14.799+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:42:14.798+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:42:14.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.838 seconds
[2023-03-22T12:42:45.721+0000] {processor.py:153} INFO - Started process (PID=54967) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:42:45.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:42:45.736+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:42:45.733+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:42:48.146+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:42:48.137+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:42:48.180+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:42:48.695+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:42:48.694+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:42:48.993+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:42:48.992+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:42:49.148+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.462 seconds
[2023-03-22T12:43:19.890+0000] {processor.py:153} INFO - Started process (PID=55030) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:43:19.897+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:43:19.913+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:43:19.903+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:43:21.372+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:43:21.367+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:43:21.421+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:43:21.478+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:43:21.478+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:43:21.595+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:43:21.595+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:43:21.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.810 seconds
[2023-03-22T12:43:51.880+0000] {processor.py:153} INFO - Started process (PID=55093) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:43:51.884+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:43:51.888+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:43:51.887+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:43:52.781+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:43:52.778+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:43:52.794+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:43:52.964+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:43:52.963+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:43:53.041+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:43:53.041+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:43:53.112+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.252 seconds
[2023-03-22T12:44:23.783+0000] {processor.py:153} INFO - Started process (PID=55162) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:44:23.788+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:44:23.793+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:44:23.793+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:44:24.911+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:44:24.907+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:44:24.931+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:44:24.963+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:44:24.962+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:44:25.077+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:44:25.077+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:44:25.128+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.364 seconds
[2023-03-22T12:44:55.455+0000] {processor.py:153} INFO - Started process (PID=55225) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:44:55.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:44:55.475+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:44:55.474+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:44:56.639+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:44:56.636+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:44:56.667+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:44:56.847+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:44:56.845+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:44:56.918+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:44:56.918+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:44:56.990+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.560 seconds
[2023-03-22T12:45:27.168+0000] {processor.py:153} INFO - Started process (PID=55288) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:45:27.175+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:45:27.179+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:45:27.179+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:45:28.257+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:45:28.255+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:45:28.276+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:45:28.312+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:45:28.311+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:45:28.416+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:45:28.415+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:45:28.462+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.307 seconds
[2023-03-22T12:45:59.117+0000] {processor.py:153} INFO - Started process (PID=55346) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:45:59.127+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:45:59.132+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:45:59.131+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:46:02.293+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:46:02.290+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:46:02.337+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:46:02.638+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:46:02.637+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:46:02.739+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:46:02.739+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:46:02.863+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.797 seconds
[2023-03-22T12:46:33.136+0000] {processor.py:153} INFO - Started process (PID=55407) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:46:33.145+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:46:33.148+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:46:33.148+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:46:36.116+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:46:36.104+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:46:36.183+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:46:36.364+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:46:36.351+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:46:36.531+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:46:36.530+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:46:36.658+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.549 seconds
[2023-03-22T12:47:06.924+0000] {processor.py:153} INFO - Started process (PID=55468) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:47:06.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:47:06.938+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:47:06.937+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:47:07.722+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:47:07.721+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:47:07.739+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:47:07.861+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:47:07.859+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:47:07.921+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:47:07.921+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:47:08.024+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.110 seconds
[2023-03-22T12:47:38.825+0000] {processor.py:153} INFO - Started process (PID=55529) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:47:38.853+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:47:38.867+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:47:38.867+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:47:40.882+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:47:40.876+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:47:40.908+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:47:41.086+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:47:41.085+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:47:41.152+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:47:41.151+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:47:41.204+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.477 seconds
[2023-03-22T12:48:11.748+0000] {processor.py:153} INFO - Started process (PID=55591) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:48:11.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:48:11.757+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:48:11.757+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:48:12.680+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:48:12.677+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:48:12.698+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:48:12.852+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:48:12.852+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:48:12.910+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:48:12.910+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:48:12.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.220 seconds
[2023-03-22T12:48:43.454+0000] {processor.py:153} INFO - Started process (PID=55651) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:48:43.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:48:43.470+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:48:43.469+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:48:44.690+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:48:44.686+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:48:44.704+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:48:44.766+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:48:44.765+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:48:44.838+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:48:44.838+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:48:44.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.462 seconds
[2023-03-22T12:49:18.321+0000] {processor.py:153} INFO - Started process (PID=55710) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:49:18.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:49:18.329+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:49:18.329+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:49:19.145+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:49:19.142+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:49:19.172+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:49:19.322+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:49:19.322+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:49:19.385+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:49:19.385+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:49:19.434+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.135 seconds
[2023-03-22T12:49:50.010+0000] {processor.py:153} INFO - Started process (PID=55772) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:49:50.014+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:49:50.019+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:49:50.018+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:49:53.630+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:49:53.629+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:49:53.675+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:49:53.819+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:49:53.819+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:49:54.008+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:49:54.008+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:49:54.111+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 4.120 seconds
[2023-03-22T12:50:24.497+0000] {processor.py:153} INFO - Started process (PID=55835) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:50:24.501+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:50:24.506+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:50:24.506+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:50:25.310+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:50:25.290+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:50:25.340+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:50:25.467+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:50:25.466+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:50:25.530+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:50:25.530+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:50:25.571+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.084 seconds
[2023-03-22T12:50:56.419+0000] {processor.py:153} INFO - Started process (PID=55903) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:50:56.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:50:56.428+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:50:56.427+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:50:57.350+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:50:57.349+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:50:57.371+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:50:57.498+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:50:57.498+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:50:57.553+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:50:57.553+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:50:57.607+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.199 seconds
[2023-03-22T12:51:28.212+0000] {processor.py:153} INFO - Started process (PID=55965) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:51:28.218+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:51:28.223+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:51:28.223+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:51:29.100+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:51:29.098+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:51:29.114+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:51:29.161+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:51:29.160+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:51:29.207+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:51:29.207+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:51:29.252+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.054 seconds
[2023-03-22T12:51:59.392+0000] {processor.py:153} INFO - Started process (PID=56027) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:51:59.398+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:51:59.403+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:51:59.403+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:52:00.144+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:52:00.142+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:52:00.156+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:52:00.182+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:52:00.182+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:52:00.232+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:52:00.232+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:52:00.270+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 0.889 seconds
[2023-03-22T12:52:30.739+0000] {processor.py:153} INFO - Started process (PID=56088) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:52:30.744+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:52:30.749+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:52:30.748+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:52:31.735+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:52:31.731+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:52:31.746+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:52:31.884+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:52:31.883+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:52:31.941+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:52:31.941+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:52:31.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.270 seconds
[2023-03-22T12:53:02.224+0000] {processor.py:153} INFO - Started process (PID=56150) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:53:02.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:53:02.232+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:53:02.232+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:53:03.465+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:53:03.462+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:53:03.479+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:53:03.525+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:53:03.524+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:53:03.573+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:53:03.573+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:53:03.611+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.400 seconds
[2023-03-22T12:53:34.584+0000] {processor.py:153} INFO - Started process (PID=56212) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:53:34.589+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:53:34.605+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:53:34.605+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:53:35.538+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:53:35.534+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:53:35.551+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:53:35.580+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:53:35.579+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:53:35.632+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:53:35.631+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:53:35.672+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.099 seconds
[2023-03-22T12:54:06.095+0000] {processor.py:153} INFO - Started process (PID=56273) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:54:06.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:54:06.108+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:54:06.107+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:54:07.281+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:54:07.278+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:54:07.298+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:54:07.467+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:54:07.466+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:54:07.527+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:54:07.526+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:54:07.581+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.497 seconds
[2023-03-22T12:54:37.808+0000] {processor.py:153} INFO - Started process (PID=56334) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:54:37.814+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:54:37.818+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:54:37.818+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:54:39.048+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:54:39.041+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:54:39.078+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:54:39.192+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:54:39.189+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:54:39.301+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:54:39.301+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:54:39.402+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.603 seconds
[2023-03-22T12:55:09.626+0000] {processor.py:153} INFO - Started process (PID=56395) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:55:09.632+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:55:09.637+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:55:09.636+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:55:10.589+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:55:10.585+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:55:10.611+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:55:10.647+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:55:10.646+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:55:10.707+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:55:10.707+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:55:10.765+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.161 seconds
[2023-03-22T12:55:40.942+0000] {processor.py:153} INFO - Started process (PID=56458) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:55:40.945+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:55:40.948+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:55:40.948+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:55:41.735+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:55:41.732+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:55:41.759+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:55:41.902+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:55:41.901+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:55:41.964+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:55:41.961+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:55:42.019+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.085 seconds
[2023-03-22T12:56:12.176+0000] {processor.py:153} INFO - Started process (PID=56519) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:56:12.182+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:56:12.189+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:56:12.188+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:56:13.168+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:56:13.164+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:56:13.184+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:56:13.243+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:56:13.242+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:56:13.304+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:56:13.304+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:56:13.343+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.177 seconds
[2023-03-22T12:56:43.517+0000] {processor.py:153} INFO - Started process (PID=56582) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:56:43.521+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:56:43.524+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:56:43.524+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:56:44.403+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:56:44.401+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:56:44.419+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:56:44.445+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:56:44.444+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:56:44.504+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:56:44.502+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:56:44.546+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.050 seconds
[2023-03-22T12:57:14.778+0000] {processor.py:153} INFO - Started process (PID=56644) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:57:14.781+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:57:14.786+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:57:14.785+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:57:15.695+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:57:15.691+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:57:15.707+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:57:15.848+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:57:15.848+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:57:15.903+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:57:15.903+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:57:15.950+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.186 seconds
[2023-03-22T12:57:46.805+0000] {processor.py:153} INFO - Started process (PID=56705) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:57:46.824+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:57:46.828+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:57:46.827+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:57:47.870+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:57:47.864+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:57:47.884+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:57:47.937+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:57:47.935+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:57:48.023+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:57:48.023+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:57:48.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.275 seconds
[2023-03-22T12:58:18.309+0000] {processor.py:153} INFO - Started process (PID=56767) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:58:18.323+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:58:18.332+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:58:18.330+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:58:21.899+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:58:21.893+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:58:21.995+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:58:22.049+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:58:22.047+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:58:22.189+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:58:22.189+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:58:22.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 4.002 seconds
[2023-03-22T12:58:52.716+0000] {processor.py:153} INFO - Started process (PID=56830) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:58:52.722+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:58:52.727+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:58:52.727+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:58:55.090+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:58:55.084+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:58:55.124+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:58:55.481+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:58:55.480+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:58:55.567+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:58:55.565+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:58:55.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.987 seconds
[2023-03-22T12:59:26.056+0000] {processor.py:153} INFO - Started process (PID=56894) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:59:26.065+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:59:26.075+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:59:26.074+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:59:26.853+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:59:26.851+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:59:26.865+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:59:26.909+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:59:26.908+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:59:26.960+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:59:26.959+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:59:26.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 0.962 seconds
[2023-03-22T12:59:57.479+0000] {processor.py:153} INFO - Started process (PID=56955) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:59:57.484+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T12:59:57.489+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:59:57.488+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:59:58.390+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:59:58.385+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T12:59:58.409+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T12:59:58.437+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:59:58.436+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T12:59:58.504+0000] {logging_mixin.py:137} INFO - [2023-03-22T12:59:58.503+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T12:59:58.546+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.076 seconds
[2023-03-22T13:00:28.901+0000] {processor.py:153} INFO - Started process (PID=57017) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:00:28.905+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:00:28.911+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:00:28.910+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:00:30.085+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:00:30.084+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:00:30.108+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:00:30.279+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:00:30.278+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:00:30.374+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:00:30.374+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:00:30.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.540 seconds
[2023-03-22T13:01:01.297+0000] {processor.py:153} INFO - Started process (PID=57089) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:01:01.308+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:01:01.324+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:01:01.320+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:01:04.103+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:01:04.095+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:01:04.153+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:01:04.298+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:01:04.297+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:01:04.406+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:01:04.405+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:01:04.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.211 seconds
[2023-03-22T13:01:35.537+0000] {processor.py:153} INFO - Started process (PID=57152) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:01:35.550+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:01:35.576+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:01:35.554+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:01:47.301+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:01:47.297+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:01:47.324+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:01:47.495+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:01:47.494+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:01:47.575+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:01:47.575+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:01:47.731+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 12.237 seconds
[2023-03-22T13:02:23.396+0000] {processor.py:153} INFO - Started process (PID=57213) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:02:23.407+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:02:23.424+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:02:23.424+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:02:24.672+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:02:24.665+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:02:24.690+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:02:24.787+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:02:24.786+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:02:24.898+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:02:24.898+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:02:24.940+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.586 seconds
[2023-03-22T13:02:55.323+0000] {processor.py:153} INFO - Started process (PID=57277) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:02:55.331+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:02:55.339+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:02:55.338+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:02:57.575+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:02:57.572+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:02:57.591+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:02:57.646+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:02:57.645+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:02:57.739+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:02:57.739+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:02:57.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.534 seconds
[2023-03-22T13:03:28.294+0000] {processor.py:153} INFO - Started process (PID=57341) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:03:28.298+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:03:28.303+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:03:28.302+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:03:29.278+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:03:29.275+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:03:29.295+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:03:29.445+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:03:29.445+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:03:29.500+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:03:29.500+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:03:29.544+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.270 seconds
[2023-03-22T13:04:00.449+0000] {processor.py:153} INFO - Started process (PID=57403) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:04:00.460+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:04:00.465+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:04:00.464+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:04:01.459+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:04:01.457+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:04:01.472+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:04:01.526+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:04:01.525+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:04:01.579+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:04:01.578+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:04:01.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.186 seconds
[2023-03-22T13:04:34.548+0000] {processor.py:153} INFO - Started process (PID=57462) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:04:34.555+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:04:34.564+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:04:34.562+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:04:35.830+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:04:35.826+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:04:35.848+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:04:35.884+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:04:35.883+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:04:35.953+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:04:35.953+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:04:36.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.483 seconds
[2023-03-22T13:05:06.527+0000] {processor.py:153} INFO - Started process (PID=57525) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:05:06.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:05:06.538+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:05:06.537+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:05:08.124+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:05:08.114+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:05:08.176+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:05:08.419+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:05:08.418+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:05:08.517+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:05:08.517+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:05:08.586+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.071 seconds
[2023-03-22T13:05:38.908+0000] {processor.py:153} INFO - Started process (PID=57588) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:05:38.916+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:05:38.924+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:05:38.922+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:05:40.426+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:05:40.421+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:05:40.445+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:05:40.511+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:05:40.509+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:05:40.609+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:05:40.609+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:05:40.661+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.769 seconds
[2023-03-22T13:06:11.892+0000] {processor.py:153} INFO - Started process (PID=57653) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:06:11.899+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:06:11.922+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:06:11.921+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:06:14.836+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:06:14.833+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:06:14.902+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:06:15.002+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:06:14.999+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:06:15.183+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:06:15.182+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:06:15.308+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.466 seconds
[2023-03-22T13:06:52.240+0000] {processor.py:153} INFO - Started process (PID=57717) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:06:52.248+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:06:52.259+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:06:52.258+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:06:54.558+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:06:54.554+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:06:54.572+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:06:54.706+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:06:54.706+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:06:54.775+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:06:54.774+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:06:54.834+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.616 seconds
[2023-03-22T13:07:25.427+0000] {processor.py:153} INFO - Started process (PID=57779) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:07:25.434+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:07:25.444+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:07:25.442+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:07:27.157+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:07:27.148+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:07:27.186+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:07:27.246+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:07:27.245+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:07:27.310+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:07:27.309+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:07:27.398+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.996 seconds
[2023-03-22T13:07:59.098+0000] {processor.py:153} INFO - Started process (PID=57840) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:07:59.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:07:59.118+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:07:59.106+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:08:00.656+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:08:00.651+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:08:00.687+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:08:00.729+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:08:00.728+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:08:00.898+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:08:00.897+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:08:00.989+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.904 seconds
[2023-03-22T13:08:34.429+0000] {processor.py:153} INFO - Started process (PID=57891) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:08:34.435+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:08:34.439+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:08:34.439+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:08:35.944+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:08:35.938+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:08:35.973+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:08:36.246+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:08:36.245+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:08:36.328+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:08:36.326+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:08:36.401+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.990 seconds
[2023-03-22T13:09:06.650+0000] {processor.py:153} INFO - Started process (PID=57951) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:09:06.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:09:06.670+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:09:06.670+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:09:07.965+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:09:07.955+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:09:07.986+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:09:08.083+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:09:08.080+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:09:08.188+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:09:08.188+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:09:08.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.632 seconds
[2023-03-22T13:09:43.873+0000] {processor.py:153} INFO - Started process (PID=58019) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:09:43.879+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:09:43.885+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:09:43.885+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:09:45.052+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:09:45.048+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:09:45.077+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:09:45.127+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:09:45.126+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:09:45.226+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:09:45.225+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:09:45.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.447 seconds
[2023-03-22T13:10:15.564+0000] {processor.py:153} INFO - Started process (PID=58077) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:10:15.576+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:10:15.599+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:10:15.594+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:10:17.329+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:10:17.317+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:10:17.387+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:10:17.601+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:10:17.600+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:10:17.679+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:10:17.679+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:10:17.737+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.195 seconds
[2023-03-22T13:10:53.690+0000] {processor.py:153} INFO - Started process (PID=58139) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:10:53.696+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:10:53.706+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:10:53.704+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:10:56.631+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:10:56.612+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:10:56.672+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:10:56.738+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:10:56.735+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:10:56.960+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:10:56.960+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:10:57.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.414 seconds
[2023-03-22T13:11:27.371+0000] {processor.py:153} INFO - Started process (PID=58200) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:11:27.380+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:11:27.392+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:11:27.391+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:11:30.325+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:11:30.318+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:11:30.379+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:11:30.767+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:11:30.766+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:11:30.906+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:11:30.906+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:11:31.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.688 seconds
[2023-03-22T13:12:02.981+0000] {processor.py:153} INFO - Started process (PID=58262) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:12:02.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:12:02.994+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:12:02.993+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:12:05.947+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:12:05.887+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:12:06.093+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:12:06.227+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:12:06.226+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:12:06.384+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:12:06.384+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:12:06.473+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.529 seconds
[2023-03-22T13:12:37.017+0000] {processor.py:153} INFO - Started process (PID=58323) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:12:37.036+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:12:37.050+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:12:37.049+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:12:40.350+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:12:40.337+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:12:40.401+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:12:40.499+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:12:40.497+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:12:40.707+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:12:40.706+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:12:40.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.892 seconds
[2023-03-22T13:13:11.221+0000] {processor.py:153} INFO - Started process (PID=58385) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:13:11.226+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:13:11.231+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:13:11.230+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:13:12.830+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:13:12.828+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:13:12.844+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:13:13.031+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:13:13.029+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:13:13.114+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:13:13.113+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:13:13.353+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.142 seconds
[2023-03-22T13:13:43.680+0000] {processor.py:153} INFO - Started process (PID=58448) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:13:43.685+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:13:43.691+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:13:43.690+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:13:44.532+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:13:44.530+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:13:44.544+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:13:44.587+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:13:44.586+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:13:44.631+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:13:44.631+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:13:44.666+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.006 seconds
[2023-03-22T13:14:14.977+0000] {processor.py:153} INFO - Started process (PID=58511) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:14:14.980+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:14:14.984+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:14:14.984+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:14:20.055+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:14:20.052+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:14:20.479+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:14:20.663+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:14:20.662+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:14:21.154+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:14:21.154+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:14:21.245+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 6.278 seconds
[2023-03-22T13:14:51.666+0000] {processor.py:153} INFO - Started process (PID=58581) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:14:51.670+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:14:51.673+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:14:51.673+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:14:52.593+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:14:52.589+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:14:52.609+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:14:52.737+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:14:52.736+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:14:52.794+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:14:52.794+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:14:52.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.191 seconds
[2023-03-22T13:15:23.631+0000] {processor.py:153} INFO - Started process (PID=58645) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:15:23.638+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:15:23.644+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:15:23.643+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:15:24.404+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:15:24.402+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:15:24.415+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:15:24.457+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:15:24.455+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:15:24.502+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:15:24.502+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:15:24.537+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 0.916 seconds
[2023-03-22T13:16:00.284+0000] {processor.py:153} INFO - Started process (PID=58705) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:16:00.296+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:16:00.299+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:16:00.299+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:16:01.192+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:16:01.188+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:16:01.211+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:16:01.259+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:16:01.258+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:16:01.319+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:16:01.318+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:16:01.359+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.086 seconds
[2023-03-22T13:16:32.178+0000] {processor.py:153} INFO - Started process (PID=58757) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:16:32.191+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:16:32.200+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:16:32.199+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:16:34.817+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:16:34.814+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:16:34.854+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:16:35.107+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:16:35.106+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:16:35.213+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:16:35.213+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:16:35.290+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 3.153 seconds
[2023-03-22T13:17:05.592+0000] {processor.py:153} INFO - Started process (PID=58822) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:17:05.595+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:17:05.600+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:17:05.599+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:17:06.901+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:17:06.894+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:17:06.958+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:17:07.034+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:17:07.032+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:17:07.127+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:17:07.126+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:17:07.197+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.613 seconds
[2023-03-22T13:17:37.686+0000] {processor.py:153} INFO - Started process (PID=58883) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:17:37.690+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:17:37.694+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:17:37.693+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:17:38.591+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:17:38.589+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:17:38.603+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:17:38.631+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:17:38.630+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:17:38.693+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:17:38.693+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:17:38.729+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.059 seconds
[2023-03-22T13:18:09.048+0000] {processor.py:153} INFO - Started process (PID=58946) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:18:09.053+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:18:09.057+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:18:09.056+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:18:10.083+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:18:10.080+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:18:10.103+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:18:10.241+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:18:10.240+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:18:10.299+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:18:10.299+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:18:10.347+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.311 seconds
[2023-03-22T13:18:40.517+0000] {processor.py:153} INFO - Started process (PID=59009) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:18:40.521+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:18:40.524+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:18:40.524+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:18:41.254+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:18:41.252+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:18:41.266+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:18:41.304+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:18:41.304+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:18:41.345+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:18:41.345+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:18:41.378+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 0.877 seconds
[2023-03-22T13:19:12.098+0000] {processor.py:153} INFO - Started process (PID=59071) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:19:12.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:19:12.107+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:19:12.107+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:19:13.453+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:19:13.451+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:19:13.472+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:19:13.501+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:19:13.499+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:19:13.591+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:19:13.591+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:19:13.647+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.563 seconds
[2023-03-22T13:19:43.799+0000] {processor.py:153} INFO - Started process (PID=59133) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:19:43.809+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:19:43.812+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:19:43.812+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:19:44.737+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:19:44.730+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:19:44.756+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:19:44.904+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:19:44.904+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:19:44.954+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:19:44.954+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:19:45.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.218 seconds
[2023-03-22T13:20:15.102+0000] {processor.py:153} INFO - Started process (PID=59198) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:20:15.106+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:20:15.112+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:20:15.112+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:20:15.799+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:20:15.796+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:20:15.812+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:20:15.876+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:20:15.874+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:20:15.975+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:20:15.974+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:20:16.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 0.942 seconds
[2023-03-22T13:20:46.700+0000] {processor.py:153} INFO - Started process (PID=59258) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:20:46.702+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:20:46.705+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:20:46.705+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:20:47.524+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:20:47.518+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:20:47.540+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:20:47.573+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:20:47.572+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:20:47.660+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:20:47.660+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:20:47.700+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.009 seconds
[2023-03-22T13:21:18.051+0000] {processor.py:153} INFO - Started process (PID=59322) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:21:18.058+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:21:18.069+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:21:18.067+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:21:19.712+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:21:19.708+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:21:19.730+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:21:19.955+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:21:19.954+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:21:20.090+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:21:20.089+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:21:20.194+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.170 seconds
[2023-03-22T13:21:50.790+0000] {processor.py:153} INFO - Started process (PID=59386) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:21:50.795+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:21:50.799+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:21:50.798+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:21:51.962+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:21:51.955+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:21:52.009+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:21:52.130+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:21:52.129+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:21:52.263+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:21:52.263+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:21:52.382+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.608 seconds
[2023-03-22T13:22:22.958+0000] {processor.py:153} INFO - Started process (PID=59457) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:22:22.962+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:22:22.976+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:22:22.976+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:22:24.654+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:22:24.650+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:22:24.670+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:22:24.710+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:22:24.709+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:22:24.788+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:22:24.788+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:22:24.830+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.895 seconds
[2023-03-22T13:22:55.120+0000] {processor.py:153} INFO - Started process (PID=59522) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:22:55.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:22:55.140+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:22:55.140+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:22:57.146+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:22:57.142+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:22:57.222+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:22:57.455+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:22:57.455+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:22:57.506+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:22:57.506+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:22:57.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 2.435 seconds
[2023-03-22T13:23:27.761+0000] {processor.py:153} INFO - Started process (PID=59585) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:23:27.773+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:23:27.781+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:23:27.779+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:23:28.592+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:23:28.590+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:23:28.602+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:23:28.642+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:23:28.642+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:23:28.682+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:23:28.682+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:23:28.714+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 0.967 seconds
[2023-03-22T13:23:58.995+0000] {processor.py:153} INFO - Started process (PID=59647) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:23:58.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:23:59.001+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:23:59.000+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:23:59.830+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:23:59.828+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:23:59.840+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:23:59.862+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:23:59.861+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:23:59.922+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:23:59.921+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:23:59.959+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 0.971 seconds
[2023-03-22T13:24:30.379+0000] {processor.py:153} INFO - Started process (PID=59708) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:24:30.384+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:24:30.389+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:24:30.388+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:24:31.209+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:24:31.207+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:24:31.225+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:24:31.381+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:24:31.380+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:24:31.429+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:24:31.429+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:24:31.490+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.145 seconds
[2023-03-22T13:25:01.808+0000] {processor.py:153} INFO - Started process (PID=59768) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:25:01.820+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:25:01.828+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:25:01.828+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:25:02.483+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:25:02.481+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:25:02.493+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:25:02.532+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:25:02.531+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:25:02.573+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:25:02.572+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:25:02.606+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 0.809 seconds
[2023-03-22T13:25:35.527+0000] {processor.py:153} INFO - Started process (PID=59825) to work on /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:25:35.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data/load_csv.py for tasks to queue
[2023-03-22T13:25:35.542+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:25:35.541+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:25:36.654+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:25:36.651+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-22T13:25:36.669+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/data/load_csv.py
[2023-03-22T13:25:36.711+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:25:36.710+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-22T13:25:36.796+0000] {logging_mixin.py:137} INFO - [2023-03-22T13:25:36.796+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to None, run_after=None
[2023-03-22T13:25:36.830+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data/load_csv.py took 1.321 seconds
